# Generated by Django 3.2 on 2021-09-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_subjectcontent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcontent',
            name='content_details',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='management.batchdetails'),
            preserve_default=False,
        ),
    ]
